- images/icon_edit_notification.svg
- src/components/accordion_card.jsx
Resolves https://github.com/dannytpeck/calendar-builder-client/issues/6
> Removed the Required column from the Edit Calendar view table, Added 'edited' icon, changed accordion to open multiple cards

- css/main.css
- src/components/accordion_card.jsx
> Add edit to the table view for start date, end date, points

- css/main.css
- package-lock.json
- src/components/accordion_card.jsx
> Print preview

- css/main.css
- src/components/accordion_card.jsx
- src/components/app.jsx
> Edit calendar title

- css/main.css
- package-lock.json
- package.json
- src/components/accordion_card.jsx
- src/components/app.jsx
- src/components/calendar_accordion.jsx
Added the react-beautiful-dnd (drag-and-drop) component.
Also updated styling to better reflect the way it was arranged prior and to work with dnd.
> Add drag-and-drop

- src/components/accordion_card.jsx
- src/components/app.jsx
- src/components/calendar_accordion.jsx
> Update drag n drop logic so it renders and also updates to airtable

- src/components/accordion_card.jsx
- src/components/add_custom_challenge.jsx
- src/components/app.jsx
- src/components/calendar_accordion.jsx
- src/components/preview_challenge_modal.jsx
OOF THIS TOOK AWHILE
but it looks very nice now 💣 🍡
> Giant refactor

- css/main.css
- src/components/accordion_card.jsx
Add tooltips/titles for hovering over the table elements for more info. Added them to icons and text for consistency.
Add pointer style to editable elements.
> Add tooltips

- css/main.css
- src/components/accordion_card.jsx
- src/components/app.jsx
Made some nit-picky updates:
* Changed saved notification color slightly
* Added fadeOut to save notification
* Added save notification to other actions:
* Calendar title
* drag actions
* row deletion
> Update save notification

- css/main.css
- src/components/accordion_card.jsx
- src/components/app.jsx
- src/components/calendar_accordion.jsx
- src/components/confirm_featured_modal.jsx
Add featured toggle functionality via modal and star icon.
> Featured toggle

- src/components/accordion_card.jsx
* Changed Featured modal content with today's lucidity
* Changed Type and Tracking column names to Tracking and Frequency, respectively
> Couple small changes

- css/main.css
- src/components/accordion_card.jsx
- src/components/app.jsx
- src/components/confirm_approve_modal.jsx
- src/components/congratulations_modal.jsx
* Resolved modals showing previous modals bug
* Made featured stars always shown
* Increased save notification delay
> Small updates

- css/main.css
- src/components/accordion_card.jsx
> Add date validation

- src/components/challenge.jsx
> Set conditional featuring of challenges

- css/main.css
- src/components/accordion_card.jsx
- src/components/challenge.jsx
> Add short-description to print view

- package.json
- src/components/app.jsx
- yarn.lock
> Fixed all the bugs with clonedeep. #perf

- src/components/app.jsx
Adding a bit of code to the congratulations close modal so it doesn't have a weird bug.
> Resolve congratulations modal closing bug

- src/components/challenge.jsx
> Make Connect with a Coach and Hot Topics on the Go appear as System Awarded

- css/main.css
- src/components/accordion_card.jsx
- src/components/app.jsx
- src/components/calendar_accordion.jsx
- src/components/challenge.jsx
- src/components/point_totals.jsx
- src/components/preview_challenge_modal.jsx
> Resolve bugs by switching to using reducers

- css/main.css
- index.html
- src/components/app.jsx
- src/components/challenge.jsx
- src/components/custom_totals.jsx
Added badges for custom tile types Net New, Rerun, and Revised.
Also added counts of each to the top of the page by the Category Totals.
> Add badges and counts for custom tiles 

- css/main.css
- index.html
- src/components/app.jsx
- src/components/challenge.jsx
All the badges.
📛  📛  📛 :rage3:
> Add custom and targeted badges

- css/main.css
- src/components/accordion_card.jsx
- src/components/add_custom_challenge.jsx
- src/components/add_custom_challenge_button.jsx
Also changed the textbox+button to "Add Placeholder Challenge" by PO request.
In the words of Rob Zombie, "So hideous."
:neckbeard:  ⚰️
> Add Create Custom Challenge button that opens blackburrow

- src/components/add_custom_challenge_button.jsx
- src/components/app.jsx
- src/components/challenge.jsx
> 11th hour updates

- src/components/challenge.jsx
> Re-enable Verified override for the 4 HP tiles

- css/main.css
- src/components/accordion_card.jsx
- src/components/category_totals.jsx
- src/components/challenge.jsx
Updated CSS table layout to prevent table rows from expanding in size when an input box is selected. :bento: 🎐 :cool:
> Modified Table Layout

- src/components/accordion_card.jsx
- src/components/app.jsx
- src/components/challenge.jsx
> Date fiddling for custom challenges

- src/components/challenge.jsx
Not a whole lot here, just really wanted to use this name once I saw the sequel subtitle.
Can you believe there are 6 Bring It On movies? What a world.
> Bug It On: Worldwide Bugsmack 

- css/main.css
- index.html
- src/components/app.jsx
- src/components/challenge.jsx
> Placeholder exceptions

- index.html
- src/components/app.jsx
Thought I'd be putting more into this PR. Oh well, back to Blackburrow dev.
> Bug squash VIII: Fate of the Bugs

- index.html
- src/components/challenge.jsx
Make all Verified just show as Verified rather than Points Upload or System Awarded.
(Self-Report and Placeholder stays the same)
> Change Verified column's front-end values
